spring.mongodb.uri=mongodb://root:secret@localhost:27017/users?authSource=admin

management.endpoints.web.exposure.include=*
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.data.mongodb=DEBUG
