apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
type: Opaque
stringData:
  root-username: {{ .Values.mongodb.rootUsername }}
  root-password: {{ .Values.mongodb.rootPassword }}
  uri: {{ printf "mongodb://%s:%s@%s:%v/%s?authSource=admin" .Values.mongodb.rootUsername .Values.mongodb.rootPassword .Values.mongodb.name (.Values.mongodb.port | toString) .Values.mongodb.database }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-user-credentials
type: Opaque
stringData:
  uri: {{ printf "mongodb://%s:%s@%s:%v/users?authSource=admin" .Values.mongodb.rootUsername .Values.mongodb.rootPassword .Values.mongodb.name (.Values.mongodb.port | toString) }}
