{{- $apps := list
  (dict "key" "webClient" "cfg" .Values.webClient)
  (dict "key" "apiGateway" "cfg" .Values.apiGateway)
  (dict "key" "userService" "cfg" .Values.userService)
  (dict "key" "contentService" "cfg" .Values.contentService)
  (dict "key" "genAi" "cfg" .Values.genAi)
-}}
{{- range $index, $app := $apps }}
{{- $cfg := $app.cfg -}}
{{- if $index }}
---
{{- end }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $cfg.name }}
  labels:
{{ include "newsGenAI.labels" (dict "name" $cfg.name "releaseName" $.Release.Name) | indent 4 }}
automountServiceAccountToken: false
{{- end }}
