spring.application.name=server

# Disable automatic Docker Compose lifecycle during local startup
# This prevents Spring Boot from looking for a docker-compose file when you run the app locally.
spring.docker.compose.enabled=false
