apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-client
  labels:
    app: web-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-client
  template:
    metadata:
      labels:
        app: web-client
    spec:
      containers:
        - name: web-client
          image: ghcr.io/aet-devops26/rolling-restarts/web-client:969a00c
          imagePullPolicy: Always
          ports:
            - containerPort: 3000

          env:
            - name: NODE_ENV
              value: "production"
            - name: NEXT_PUBLIC_API_BASE_URL
              value: "http://spring-api:8080"

          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"