---
project_root: /opt/rolling-restarts
compose_file: docker-compose.yaml
compose_prod_file: docker-compose.prod.yaml
compose_env_path: .env
app_service_name: rolling-restarts
health_check_retries: 60
health_check_delay: 20

registry: ghcr.io/aet-devops26/team-the-rolling-restarts
registry_user: ""
registry_token: ""
image_tag: latest
