apiVersion: v1
kind: Service
metadata:
  name: grafana-lgtm
  namespace: monitoring-rolling-restarts
spec:
  selector:
    app: grafana-lgtm
  ports:
    - name: grafana
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: otlp-grpc
      protocol: TCP
      port: 4317
      targetPort: 4317
    - name: otlp-http
      protocol: TCP
      port: 4318
      targetPort: 4318
  type: ClusterIP
