openapi: 3.0.3
info:
  title: OpenAPI definition
  version: v0
  license:
    url: https://unlicense.org
    name: UNLICENSED
servers:
  - url: /
security: []
paths:
  /test:
    get:
      tags:
        - root-controller
      operationId: test
      summary: Get test message
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "400":
          description: Bad Request
  /:
    get:
      tags:
        - root-controller
      operationId: root
      summary: Get root message
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "400":
          description: Bad Request
  /dummy:
    get:
      tags:
        - root-controller
      operationId: dummy
      summary: Get dummy message
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Message"
        "400":
          description: Bad Request
components:
  schemas:
    Message:
      type: object
      properties:
        message:
          type: string
